services:
  app:
    build:
      context: .
    command: >
      sh -c "python webapp/manage.py wait_for_db &&
             python webapp/manage.py migrate &&
             python webapp/manage.py runserver 0.0.0.0:8000"
             
    ports: 
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aditya2003
    depends_on:
      - pg


  pg:
    image: dpage/pgadmin4 
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin123