name: Build, Analyze, Scan
on: 
    push:
        branches:
            - main

jobs:
    build_analyze_scan:
        name: Build, Analyze, Scan
        runs-on: ubuntu-latest    #[self-hosted]
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Python 3.11
              uses: actions/setup-python@v2
              with:
                  python-version: 3.11

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Docker Build and Push
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
              run: |
                  docker-compose -f docker-compose.yaml build
                  docker tag webapp:latest adityasarade/webapp:latest
                  docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                  docker push adityasarade/webapp:latest